apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@hugecat.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # Use Azure DNS for DNS-01 challenge
      - dns01:
          azureDNS:
            subscriptionID: 79307c77-54c3-4738-be2a-dc96da7464d9
            resourceGroupName: nekoc
            hostedZoneName: hugecat.net
            managedIdentity:
              clientID: e502213f-1f15-4f03-9fb4-b546f51aafe9
