apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-disable-mtls
  namespace: default
spec:
  host: redis-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
