apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: chat-backend-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-backend
  updatePolicy:
    updateMode: 'Auto' # Set to "Auto" to enable automatic updates
  resourcePolicy:
    containerPolicies:
      - containerName: istio-proxy
        mode: 'Off'
