apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: chat-frontend-dns
  namespace: prod
spec:
  name: chat-ui.hugecat.net.
  type: A
  ttl: 300
  managedZoneRef:
    name: hugecat-net-zone
  rrdatas:
    - '34.31.128.59' # LoadBalancer IP - frontend now served from backend pod
