apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  annotations:
    # Azure Load Balancer specific annotations
    service.beta.kubernetes.io/azure-load-balancer-internal: 'false'
spec:
  type: ClusterIP
  selector:
    app: chat-backend
  ports:
    - name: http
      port: 80
      targetPort: 5001
      protocol: TCP
