apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: chat-virtualservice
  namespace: prod
spec:
  hosts:
    - 'chat-backend.hugecat.net'
    - 'chat-ui.hugecat.net' # Frontend now served from backend pod
  gateways:
    - chat-gateway
  http:
    - match:
        - uri:
            prefix: /.well-known/acme-challenge
      route:
        - destination:
            host: cm-acme-http-solver-hx6fx
            port:
              number: 8089
    - match:
        - uri:
            prefix: /api/socket.io
      route:
        - destination:
            host: chat-backend.prod.svc.cluster.local
            port:
              number: 80
      headers:
        request:
          set:
            Connection: upgrade
            Upgrade: websocket
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: chat-backend.prod.svc.cluster.local
            port:
              number: 80
