apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - secret.yaml
  - redis-secret.yaml
  - redis-service.yaml
  - secretproviderclass.yaml
  - istio-gateway.yaml
  - istio-virtualservice.yaml
